language: rust

rust:
    - stable
    - beta
    - nightly

before_install:
    - sudo apt-get update

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
        sources:
            - kalakris-cmake
install:
    - wget https://github.com/jedisct1/libsodium/releases/download/1.0.12/libsodium-1.0.12.tar.gz
    - tar xvfz libsodium-1.0.12.tar.gz
    - cd libsodium-1.0.12 && ./configure && sudo make && sudo make install
    - sudo ldconfig /usr/local/lib

before_script:
    - cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH

script:
    - cargo build --verbose
    - cargo test --verbose
    # - cargo bench --verbose
    # - cargo doc --verbose

after_success:
    - cargo coveralls
