sudo: false
language: rust

rust:
    - stable
    - beta
    - nightly

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
        sources:
            - kalakris-cmake

before_script:
    - cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo bench --verbose
    - cargo doc --verbose

after_success:
    - cargo coveralls
