[package]
name = "libyobicash"
version = "0.1.0"
authors = ["Christian Nyumbayire <chritchens@gmail.com>"]
links = "ctaes"
build = "build.rs"

[build-dependencies]
cc = "^1"

[dependencies]
chrono = "^0.4"
semver = "^0.8"
bigint = "^4.2"
rand = "^0.3"
byteorder = "^1.1"
subtle = "^0.2"
arrayref = "^0.3"
typenum = "^1.9"
generic-array = "^0.8"
digest = "^0.6"
sha2 = "^0.6"
hmac = "^0.4"
hkdf = "^0.2"
curve25519-dalek = "^0.11"
rust-crypto = "^0.2"
error-chain = "^0.11"
rustc-serialize = "^0.3"
libc = "^0.2"
