[package]
name = "libyobicash"
version = "0.5.0"
authors = ["Christian Nyumbayire <chritchens@gmail.com>"]
license = "MIT"
description = "Library of the Yobicash cryptocurrency"
repository = "https://github.com/yobicash/libyobicash"
readme = "README.md"
keywords = ["library", "cryptocurrency", "storage", "network", "p2p"]
categories = ["cryptography", "database", "network-programming"]
build = "build.rs"
links = "sodium"

[badges]
travis-ci = { repository = "yobicash/libyobicash", branch = "master" }
coveralls = { repository = "yobicash/libyobicash", branch = "master", service = "github" }

[dependencies]
libc = "*"
error-chain = "^0.10.0"
serde = "^1"
serde_derive = "^1"
num-bigint = "^0.1"
num-traits = "^0.1"
itertools = "^0.6.0"
byteorder = "^1"
semver = { version = "^0.7", features = ["serde"] }
chrono = { version = "^0.4", features = ["serde"] }

[build-dependencies]
pkg-config = "*"
